### ISSUE TITLE
[BUG] A DNS label is empty.

### ISSUE THREAD

**Issue by clioyen** [Flax-Network/flax-blockchain#17]
**Describe the bug**
I tried to install the Flax, after installation the UI is keep syncing, and the log show

2021-07-02T14:49:23.530 full_node flax.full_node.full_node: ERROR    Exception: A DNS label is empty.
2021-07-02T14:49:23.531 full_node flax.full_node.full_node: ERROR    Exception in peer discovery: A DNS label is empty.
2021-07-02T14:49:23.531 full_node flax.full_node.full_node: ERROR    Exception Stack: Traceback (most recent call last):
  File "flax\full_node\full_node.py", line 194, in set_server
  File "flax\server\node_discovery.py", line 476, in __init__
  File "flax\server\node_discovery.py", line 66, in __init__
  File "dns\resolver.py", line 732, in __init__
  File "dns\resolver.py", line 928, in read_registry
  File "dns\resolver.py", line 891, in _config_win32_fromkey
  File "dns\resolver.py", line 854, in _config_win32_domain
  File "dns\name.py", line 942, in from_text
dns.name.EmptyLabel: A DNS label is empty.

I have turn off firewall and window virus protection, I also try to uninstall Flax and clean the Flax temp file, but problem still occur.

**Screenshots**

![flax01](https://user-images.githubusercontent.com/24953137/124234183-4a8ed380-db46-11eb-9d61-e8afaf113398.jpg)
![flax02](https://user-images.githubusercontent.com/24953137/124234207-511d4b00-db46-11eb-8c0d-796ce0cbb0dd.jpg)

**Desktop (please complete the following information):**

- OS: Window 10
- CPU: AMD Ryzen 9 5950X

**Comment by flax-dev** [comment]
I think maybe your ISP is filtering the DNS entries for `dns-introducer.flaxnetwork.org`. Is it possible for you to use another DNS server?
