### ISSUE TITLE
[BUG] Flax wiritng 1 TB of log every day

### ISSUE THREAD

**Issue by JariNestel** [Flax-Network/flax-blockchain#39]
**Describe the bug**
Flax is writing 1 TB of log every day

**To Reproduce**

1. install
2. start
3. log into wallet

**Expected behavior**
Not 1 TB of log per day

**Desktop**
- OS: Windows 10
- OS Version/Flavor: 10.0.19043 Build 19043
- CPU: AMD Ryzen 5 3600

**Additional context**
I've been getting into Taco in combination with multiple other forks, most seem to have this problem, I've checked if there are port collisions, there aren't.
Others are: Chaingreen, Chia, Covid, DogeChia, Silicon, Taco

**Comment by JariNestel** [comment]
I've tested this again with the newest version and a clean start of Windows.
As soon as the full node is connected to its first peer the log is just full of this roughly 1000 times per second.
```
2021-09-05T11:37:49.004 daemon asyncio: ERROR Exception in callback BaseSelectorEventLoop._read_from_self()
handle: <Handle BaseSelectorEventLoop._read_from_self()>
Traceback (most recent call last):
  File "asyncio\events.py", line 88, in _run
  File "asyncio\selector_events.py", line 119, in _read_from_self
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host.
```
