### ISSUE TITLE
[BUG] error: database is locked

### ISSUE THREAD

**Issue by jfikar** [Flax-Network/flax-blockchain#58]
Hi, I'm recently getting a strange error about locked database when doing e.g. `flax show -s` or `flax farm summary`

I'm on Linux CLI with Python 3.9 and haven't seen the error on any other fork. When I restart flax, the problem is gone. I do `flax stop -d all`. But there are four stuck processes afterwards `flax_full_node_worker`. You need to do `pkill -9 flax` and then `flax start farmer`.

```
$ flax show -s
Exception from 'show' Traceback (most recent call last):
  File "/home/pi/flax-blockchain/flax/cmds/show.py", line 93, in show_async
    blockchain_state = await client.get_blockchain_state()
  File "/home/pi/flax-blockchain/flax/rpc/full_node_rpc_client.py", line 32, in get_blockchain_state
    response = await self.fetch("get_blockchain_state", {})
  File "/home/pi/flax-blockchain/flax/rpc/rpc_client.py", line 49, in fetch
    raise ValueError(res_json)
ValueError: {'error': 'database is locked', 'success': False}

**Comment by jfikar** [comment]
I'm still getting "database is locked" with 0.1.10

**Comment by jfikar** [comment]
It seems 0.1.11 fixed the problem.
