### ISSUE TITLE
error in log file:

### ISSUE THREAD

**Issue by BianKo666niglio** [Flax-Network/flax-blockchain#7]
in my log file I have this error message:

2021-06-24T19:59:21.327 full_node full_node_server        : ERROR    Exception Was not able to get peername from <function WSFlaxConnection.__getattr__.<locals>.invoke at 0x0000020F3A8AE558> at 68.47.82.88, exception Stack: Traceback (most recent call last):
  File "flax\server\server.py", line 248, in incoming_connection
  File "flax\server\ws_connection.py", line 59, in __init__
ValueError: Was not able to get peername from <function WSFlaxConnection.__getattr__.<locals>.invoke at 0x0000020F3A8AE558> at 68.47.82.88

2021-06-24T21:01:13.653 full_node full_node_server        : ERROR    Exception Was not able to get peername from <function WSFlaxConnection.__getattr__.<locals>.invoke at 0x0000020F399EA048> at 92.176.169.98, exception Stack: Traceback (most recent call last):
  File "flax\server\server.py", line 248, in incoming_connection
  File "flax\server\ws_connection.py", line 59, in __init__
ValueError: Was not able to get peername from <function WSFlaxConnection.__getattr__.<locals>.invoke at 0x0000020F399EA048> at 92.176.169.98

what does it means?

**Comment by flax-dev** [comment]
I don't think this is an issue -- it is likely a transient warning message.
