### ISSUE TITLE
Error en log [BUG]

### ISSUE THREAD

**Issue by vjuagar** [Flax-Network/flax-blockchain#8]
I find this error in log file:

2021-06-25T14:16:53.915 farmer farmer_server              : WARNING  Connecting peer {'host': '127.0.0.1', 'port': 8778}
2021-06-25T14:16:56.809 full_node full_node_server        : WARNING  Connecting peer {'host': '127.0.0.1', 'port': 8749}
2021-06-25T14:17:01.682 full_node full_node_server        : ERROR    Exception:  <class 'concurrent.futures._base.CancelledError'>, closing connection {'host': '127.0.0.1', 'port': 8749}. Traceback (most recent call last):
  File "chaingreen\server\server.py", line 548, in api_call
  File "asyncio\tasks.py", line 435, in wait_for
concurrent.futures._base.CancelledError

2021-06-25T14:17:01.690 full_node full_node_server        : WARNING  Connecting peer {'host': '127.0.0.1', 'port': 8777}
2021-06-25T14:17:02.835 full_node full_node_server        : WARNING  Connecting peer {'host': '127.0.0.1', 'port': 8749}

**Comment by flax-dev** [comment]
This is flax, not chaingreen.
